export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_SELECTEDIMAGE = "SET_SELECTEDIMAGE";
export const SET_FULLSCREENSTATUS = "SET_FULLSCREENSTATUS";
export const SET_ACTIONBARDISPLAY = "SET_ACTIONBARDISPLAY";